Refactor
hankaEsha/pexeso pull request #7
Opened 2022-03-29 08:25 UTC by hankaEsha

naming, order, emoji swap

2022-03-30 12:52 UTC, katemihalikova requested changes

2022-03-30 12:52 UTC, katemihalikova commented on script.js
>          setTimeout(turnCardsBack, 500);
Tady by se mi líbilo u funkcí `turnCardsOut` a `turnCardsBack`
* buď arrow funkci neukládat do proměnné, ale strčit ji celou do `setTimeout` přímo
* a nebo přesunout obě funkce úplně ven, tam, co byla původně jen funkce `turnCardsBack` (obě funkce nepotřebují žádnou lokální proměnnou ani žádný parametr a není potřeba je při každém kliknutí definovat znovu)

2022-03-30 12:52 UTC, katemihalikova commented on script.js
> +  playground.addEventListener("click", handleMove);
Při každé nové hře se event listener přidá znovu, takže se pk postupně kumulují.
* Buď tenhle řádek přesunout zpět, kde byl _(lepší)_
* a nebo při dohrání hry použít `removeEventListener`

2022-03-30 12:52 UTC, katemihalikova commented on script.js
> +  playground.addEventListener("click", handleMove);
Při každé nové hře se event listener přidá znovu, takže se pk postupně kumulují.
* Buď tenhle řádek přesunout zpět, kde byl _(lepší)_
* a nebo při dohrání hry použít `removeEventListener`

2022-03-30 12:52 UTC, katemihalikova commented on script.js
>      numbersList[number]++;
Líbilo by se mi
* buď kód lehce zjednodušit s pomocí `do`/`while` smyčky (aby se neopakoval kód s generováním dvakrát)
* a nebo na to jít opačně, nejprve si připravit "karty" a pak je zamíchat pomocí některého algoritmu na náhodné zamíchání pole, třeba něco jako `let emojiToPutOnCards = shuffle([...emoji.slice(0, size), ...emoji.slice(0, size)]);` (`shuffle` nevymýšlej, ale zkopíruj např. [odtud](https://stackoverflow.com/a/12646864/3603869), část _EDIT: Updating to ES6_)

2022-03-30 12:52 UTC, katemihalikova commented on script.js
>      numbersList[number]++;
Líbilo by se mi
* buď kód lehce zjednodušit s pomocí `do`/`while` smyčky
* a nebo na to jít opačně, nejprve si připravit "karty" a pak je zamíchat pomocí některého algoritmu na náhodné zamíchání pole, třeba něco jako `let emojiToPutOnCards = shuffle([...emoji.slice(0, size), ...emoji.slice(0, size)]);` (`shuffle` nevymýšlej, ale zkopíruj např. [odtud](https://stackoverflow.com/a/12646864/3603869), část _EDIT: Updating to ES6_)

2022-04-08 13:50 UTC, benabraham commented on script.js
> +const startGame = (event) => {
lepší název

2022-04-11 12:07 UTC, katemihalikova approved these changes
Super, dobrá práce, jsem spoko 👍 Přidala jsem drobný nápad na vylepšení, ale není nutno řešit.

2022-04-11 12:07 UTC, katemihalikova commented on script.js
>          setTimeout(turnCardsBack, 500);
Tady by se mi líbilo u funkcí `turnCardsOut` a `turnCardsBack`
* buď arrow funkci neukládat do proměnné, ale strčit ji celou do `setTimeout` přímo
* a nebo přesunout obě funkce úplně ven, tam, co byla původně jen funkce `turnCardsBack` (obě funkce nepotřebují žádnou lokální proměnnou ani žádný parametr a není potřeba je při každém kliknutí definovat znovu)

2022-04-11 12:07 UTC, katemihalikova commented on script.js
> +  let emojiToPutOnCards = shuffleArray([...emoji.slice(0, cardsCount/2), ...emoji.slice(0, cardsCount/2)]);
Návrh na vylepšení: Úplně moc bych skákala do stropu radostí, kdyby se náhodně vybírala i emoji, která se pak dávají na karty :)

2022-04-14 10:37 UTC, merged